"""Generate docs/prompts.md from the source, verbatim.

Every prompt the experiment sends lives as a constant in `reviewbot/`. Nothing
in the docs reproduced them, which is a gap: the first question a skeptical
reader asks about "the only difference is the memory layer" is *what did you
actually tell the model*, and the answer should not require reading Python.

Generated rather than hand-written so it cannot drift from the code.
`tests/test_prompts.py` fails if this file is stale.

    python3 tools/dump_prompts.py            # write docs/prompts.md
    python3 tools/dump_prompts.py --check    # exit 1 if it is out of date
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from reviewbot.agents import PRIMER_SCHEMA, PRIMER_SYSTEM, WRITE_SCHEMA, WRITE_SYSTEM
from reviewbot.review import (
    FINDINGS_SCHEMA,
    SYSTEM_PROMPT,
    conventions_block,
    prior_knowledge_block,
    source_context_block,
)

OUT = ROOT / "docs/prompts.md"

HEADER = """<!-- GENERATED by tools/dump_prompts.py -- do not edit by hand.
     Edit the constants in reviewbot/ and re-run the tool. -->

# Every prompt this experiment sends

Reproduced verbatim from the source, because "the only difference between the two
agents is a memory layer" is a claim about prompts, and a reader should be able to
check it without reading Python. `tests/test_prompts.py` fails if this file drifts
from the code.

There are four model calls in the experiment, and only **one** of them differs
between the agents — and it differs only in which context blocks are present:

| Phase | Who runs it | Prompt |
|---|---|---|
| `review` | **both agents** | the same frozen `SYSTEM_PROMPT` below |
| `prime`  | memory agent only, once per repo | `PRIMER_SYSTEM` |
| `write`  | memory agent only, after each review | `WRITE_SYSTEM` |
| `retrieve` | memory agent only | not a model call — a store search; the query text is below |

## The confound this design is guarding

The review system prompt is **byte-identical for both agents**, and it names the
optional `Prior knowledge` section explicitly. That is deliberate: if the prompt
described only the sections a given agent supplies, the two agents would send
different bytes, and every token comparison would be confounded by prompt length
as well as by prompt content. Instead, both agents send the same instructions and
the *presence or absence of blocks* is the whole difference.
"""


def fence(text: str, lang: str = "text") -> str:
    return f"```{lang}\n{text}\n```"


def build() -> str:
    parts = [HEADER]

    parts.append("## 1. `review` — the shared system prompt (both agents)\n")
    parts.append(
        "Sent by the baseline and the memory agent, unchanged, on every PR. "
        "`reviewbot/review.py::SYSTEM_PROMPT`.\n"
    )
    parts.append(fence(SYSTEM_PROMPT))

    parts.append("\n### The user-turn blocks, in order\n")
    parts.append(
        "`build_request()` assembles these. The prompt-cache breakpoint sits at the "
        "end of the last **stable** block, so the conventions are cached and the "
        "per-PR material is not.\n"
    )
    parts.append(
        "| # | Block | baseline | memory agent |\n"
        "|---|---|---|---|\n"
        "| 1 | `Repo conventions:` (stable, cached) | yes | yes |\n"
        "| 2 | `Prior knowledge:` (retrieved memories) | **never** | when retrieval returns anything |\n"
        "| 3 | `Source context:` (full text of touched files) | **every PR** | never |\n"
        "| 4 | `The diff:` (unified patches) | yes | yes |\n"
    )
    parts.append(
        "\nBlock 2 versus block 3 *is* the experiment: the baseline re-reads source "
        "to rebuild its understanding of the repo, the memory agent reads a distilled "
        "slice of what was already understood.\n"
    )

    parts.append("\nRendered shapes, from the block builders:\n")
    parts.append(
        fence(
            conventions_block({"CONTRIBUTING.md": "<file text>"})["text"]
            + "\n\n"
            + source_context_block({"redis/connection.py": "<file text>"})["text"]
            + "\n\n"
            + prior_knowledge_block(
                [
                    ("conv-redis-connection-py-socket-lifecycle", "<one durable fact>"),
                    ("find-redis-cluster-py-slot-cache-lock-7", "<a past finding>"),
                ]
            )["text"]
        )
    )
    parts.append(
        "\nMemory ids are exposed in the `Prior knowledge` block on purpose: the model "
        "is asked to list the ones it relied on in `memories_used`, which is the "
        "retrieval-precision signal (spec §7b). Without the ids there is no way to tell "
        "20-retrieved-3-used from 20-retrieved-20-used.\n"
    )

    parts.append("\n### Structured output for a review\n")
    parts.append(fence(json.dumps(FINDINGS_SCHEMA, indent=2), "json"))

    parts.append("\n## 2. `prime` — building repo knowledge once (memory agent only)\n")
    parts.append(
        "One call per spine module, at `pr_ordinal=0`, before the sequence starts. "
        "Per-module rather than one big call so re-priming a single changed module does "
        "not re-pay for the rest. `reviewbot/agents.py::PRIMER_SYSTEM`.\n"
    )
    parts.append(fence(PRIMER_SYSTEM))
    parts.append("\n" + fence(json.dumps(PRIMER_SCHEMA, indent=2), "json"))

    parts.append("\n## 3. `write` — distilling findings into memories (memory agent only)\n")
    parts.append(
        "Runs after each review that produced findings. This is a **measured model "
        "call**, not free bookkeeping: its tokens are in the memory agent's column, "
        "which is why savings can be reported net of overhead. `--no-distill` swaps it "
        "for a zero-model-token variant that writes findings verbatim.\n"
    )
    parts.append(fence(WRITE_SYSTEM))
    parts.append("\n" + fence(json.dumps(WRITE_SCHEMA, indent=2), "json"))
    parts.append(
        "\nThe `module` field is a **retrieval key matched by exact string equality**, "
        "not a description. A model-supplied value is resolved against the PR's touched "
        "files before it becomes a topic (`memory.resolve_modules`) — on the first real "
        "run, 5 of 6 written findings named a directory rather than a file and would "
        "have been unretrievable forever. See spec §4d.\n"
    )

    parts.append("\n## 4. `retrieve` — the search query (memory agent only)\n")
    parts.append(
        "Not a model call. The query text is built from the PR itself, and deliberately "
        "contains **no PR number and no timestamp**: it is prompt-adjacent, and an "
        "identifier in it would make retrieval incomparable across runs.\n"
    )
    parts.append(fence('f"{pr.title}. Files changed: {modules}"', "python"))
    parts.append(
        "\nScoped by `filterOp: all` with `namespace eq`, `memoryType in "
        "[repo_convention, review_finding]`, and `topics in [touched files]`. The "
        "filter shape is load-bearing and non-obvious — see spec §4d and "
        "`reviewbot/memory.py`.\n"
    )

    parts.append("\n## What is NOT sent\n")
    parts.append(
        "- **No tools.** Neither agent has tool access; context is assembled by the "
        "harness, so token accounting is exact rather than dependent on what a model "
        "chose to fetch.\n"
        "- **No assistant prefill.** It returns a 400 on this model; structured output "
        "comes from `output_config.format`.\n"
        "- **No PR number, date, or run id anywhere in a cached prefix.** Any of those "
        "would silently zero the prompt cache, and a cache miss reads as context volume.\n"
    )
    return "\n".join(parts) + "\n"


def main(argv: list[str]) -> int:
    text = build()
    if "--check" in argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is stale -- re-run: python3 tools/dump_prompts.py")
            return 1
        print(f"{OUT} is up to date")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
